apiVersion: v1
kind: Service
metadata:
  name: ${projectname}-service
  namespace: ${namespace}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: ${nodePort}
  selector:
    app: ${projectname}-deployment
